# config.yaml
start_date: "2023-03"     # 计算起始月份 (YYYY-MM)
end_date: "2024-11"       # 计算结束月份
monthly_salary: 7000     # 初始月薪

# 五险一金比例配置
insurance_rates:
  pension: 0.08          # 养老保险个人比例
  unemployment: 0.005    # 失业保险个人比例
  medical: 0.02          # 医疗保险个人比例
housing_fund_rate: 0.12  # 住房公积金个人比例
# monthly_special_deduction: 0 #专项扣除，如房租

# 初始累积数据
initial_accumulated:
  income: 14000
  special_deduction: 3150
  tax_paid: 25.5

# 调薪记录（可选）
salary_adjustments:
  - date: "2023-06"
    new_salary: 8000
  - date: "2023-09"
    new_salary: 12000

# 新增请假配置（实际工作天数）
leave_days:
  "2023-03": 20   
  "2024-11": 15   
